### ISSUE TITLE
support with Chinese filepath and multiple filepaths

### ISSUE THREAD

**Issue by coolit** [gregoryyoon/dropfiles_window#4]
It didn't seem to work if the path of dropped file is Chinese or if they are multiple files.

**Comment by gregoryyoon** [comment]
Hello @coolit 

ok. I will try to fix the path problem in Chinese and to support multiple files as well.

Thanks

**Comment by coolit** [comment]
hi thanks for responding, maybe there is no need to bother, since another package has already done that. Thanks anyway.
